name = "wholesale-sync"
main = "worker.js"
compatibility_date = "2026-01-01"

[vars]

[[d1_databases]]
binding = "DB"
database_name = "salim-traders-db"
database_id = "8b7122ba-f0ac-4bf2-b766-f5ea4e74ee18"
